# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: music_development
  pool: 5
  timeout: 5000
  username: roman
  password: #Password

test:
  adapter: postgresql
  encoding: unicode
  database: music_test
  pool: 5
  timeout: 5000
  username: roman
  password: #Password

production:
  adapter: postgresql
  encoding: unicode
  database: music_test
  pool: 5
  timeout: 5000
  username: roman
  password: #Password
